
spring.application.name=wms
spring.profiles.active=dev

server.address=0.0.0.0

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/stocknegoce
spring.datasource.username=postgres
spring.datasource.password=Djaltek30

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public


spring.output.ansi.enabled=always
logging.level.org.springframework.security.web=TRACE
logging.level.org.hibernate.SQL=DEBUG


spring.main.allow-bean-definition-overriding=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

# JWT
jwt.secret=stocknegoce-wms-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=172800000